#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: Replace Fake Newsletter Widget with Substack Integration

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting Static Website (Python HTTP Server)..."
cd /Users/abediaz/Documents/GitHub/abediaz.ai

# Kill any existing server on port 8000
if lsof -Pi :8000 -sTCP:LISTEN -t >/dev/null 2>&1; then
    echo -e "${YELLOW}Port 8000 already in use, killing existing process...${NC}"
    kill -9 $(lsof -Pi :8000 -sTCP:LISTEN -t) 2>/dev/null || true
    sleep 1
fi

# Start Python HTTP server in background
python3 -m http.server 8000 > /dev/null 2>&1 &
SERVER_PID=$!

# Save PID for cleanup
echo $SERVER_PID > .auto-claude/specs/015-analyze-what-is-this-feature-in-the-website-actual/.server_pid

# Wait for service to be ready
wait_for_service 8000 "Static Website"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Static Website: http://localhost:8000"
echo ""
echo "To stop the server:"
echo "  kill \$(cat .auto-claude/specs/015-analyze-what-is-this-feature-in-the-website-actual/.server_pid)"
echo ""
echo "Next Steps:"
echo "  1. Open http://localhost:8000 in your browser"
echo "  2. Verify the current fake newsletter widget is visible"
echo "  3. Run the coder agent to implement the changes"
echo ""
